<template>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Contact</h5>
            <p class="card-text">
                <address>
                    <strong>Pizza Planet</strong><br>
                    Address Line 1<br>
                    Address Line 2<br>
                    Phone: (123) 456-7890<br>
                </address>
                <address>
                    <strong>Email:</strong><br>
                    <p>contact@pizzaplanet.com</p>
                </address>
            </p>
        </div>
    </div>
</template>

<script>
export default {
    
}
</script>